name: Python application

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: Test with pytest and coverage
      run: |
        pytest tests/ --cov=.

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:latest

    - name: Run Docker container
      run: |
        docker run my-image-name:latest

    - name: Deploy Application
      if: always()
      run: |
        echo "::group::Starting Deployment"
        echo "::notice::Deployment skipped in this workflow example"
        echo "::endgroup::"
