name: Python application

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --max-line-length=127 --statistics

    - name: Test with pytest and coverage
      run: pytest --cov=.

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest

    - name: Run Docker container
      run: docker run my-image-name:latest

       steps:
  - name: Checkout Code
    uses: actions/checkout@v3
    run: echo "Code has been checked out successfully"

  - name: Run Tests
    run: |
      echo "::group::Starting Tests"
      pytest tests/
      echo "::endgroup::"
      echo "::notice::All tests passed successfully"

  - name: Deploy Application
    run: echo "::error::Deployment failed. Please check configurations."
